### ISSUE TITLE
Add Honeycomb formatted trace context propagator

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-opentelemetry-dotnet#128]
**Is your feature request related to a problem? Please describe.**
When introducing the distro to an already instrumented environment with beelines, it can be a significant effort to coordinate updating all beeline instrumented services to use the W3C propagator at the same time.

The OpenTelemtry SDK only supports W3C trace propagation by default so trace context going from a beeline instrumented app using HNY formatted trace context headers -> OpenTelemetry instrumented app would lost trace contact and result in broken traces.

**Describe the solution you'd like**
Create a Honeycomb propagator and add it to the list of default propagators when configuring the OpenTelemetry SDK.

**Describe alternatives you've considered**
Alternative is to force users to update all services to use W3C trace headers and get broken traces until they all have been. I don't think many users would do that, so would reduce the likelihood of them not using this distro.

**Additional context**
_Originally raised by Eric Sampson via Honeycomb Pollinators Slack group._

**Comment by bdarfler** [comment]
Rather than go this route we intend to teach the beelines how to parse both HNY headers and w3c headers, whichever the incoming request provides. This will allow beeline users who would like to switch to OTel to incrementally update to the latest beelines, then incrementally switch the beelines from sending HNY headers to sending w3c headers, before introducing OTel.

While we recognize that the approach in this issue would help folks migrate, it doesn't pave a path towards the OTel future and creates barriers when interacting with other parts of the OTel world that won't know how to use HNY headers.

That said if folks want to explore this option for their use case it does seem possible as the propagation is pluggable and there are a few different ones that you could pattern off of.
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Api/Context/Propagation
