### ISSUE TITLE
Naming bikeshed

### ISSUE THREAD

**Issue by cartermp** [honeycombio/honeycomb-opentelemetry-dotnet#274]
Some naming questions:

Should this namespace be `OpenTelemetry.Trace`? Or `Honeycomb.OpenTelemetry`?
https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/blob/main/src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/TracerProviderBuilderExtensions.cs#L3

Should this namespace be `Honeycomb.OpenTelemetry.AutoInstrumentations`? or Honeycomb.OpenTelemetry`?
https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/blob/main/src/Honeycomb.OpenTelemetry.AutoInstrumentations/TracerProviderBuilderExtensions.cs#L4

Should the name be `AddAllInstrumentation` or something else, like `AddAutoInstrumentations`?
https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/blob/main/src/Honeycomb.OpenTelemetry.AutoInstrumentations/TracerProviderBuilderExtensions.cs#L16

Environment variables
https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/pull/275

(maybe add more)

**Comment by MikeGoldsmith** [comment]
I agree, we should use the OpenTelemetry namespaces when providing extensions methods for a class in the SDK. eg, if `AddHoneycomb()` was under OpenTelemetry.Trace, users wouldn't need to add our namespace to their imports.

For things owned by us, I think we should use Honeycomb.OpenTelemetry so it matches our package name. eg `HoneycombOptions`.

I think I prefer `AddAutoIntrumentation` vs `AddAllInstrumentation` because all could be misunderstood as adding all instrumentation from all sources instead of the specific ones we pick.
