### ISSUE TITLE
circleci nightly workflow not building properly

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-dotnet#293]
circleci nightly workflow not building properly

[Shows status Unauthorized](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-dotnet?branch=main), though regular pushes to main worked fine so it's something with the nightly workflow.

![dotnet-circleci](https://user-images.githubusercontent.com/29520003/193664588-f19b96b1-85d1-4471-8832-85075cae3896.png)

**Comment by vreynolds** [comment]
it's unauthorized because we're trying to use a secret context for the `package` step in nightly: 
```
context: Honeycomb Secrets for Public Repos
```

secrets are not available to scheduled workflows

buuut [scheduled workflows](https://circleci.com/docs/workflows#scheduling-a-workflow) are being phased out replaced by [scheduled pipelines](https://circleci.com/docs/scheduled-pipelines), which have access to restricted contexts
