### ISSUE TITLE
Publish alpha release to nuget

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-dotnet#56]
We have to do a dance with the package that already exists. Consider 0.10-alpha.

- [x] Ensure CS is aware of the change in case any customers get tripped up by it. https://docs.honeycomb.io/getting-data-in/dotnet/ shows how to use otlp exporter instead -- left a message in [Slack](https://houndsh.slack.com/archives/C8RP24A6Q/p1626212185209300)
- [x] Remove individual owners of the package
- [x] Replace nuget API key with shared key in CircleCI secrets (currently uses a key from @MikeGoldsmith)
- [x] Reach out to owner of the previous package
- [x] post in Pollinators #sdk-dotnet that the NuGet package Honeycomb.OpenTelemetry is metamorphosing from an OTel Exporter (<= 0.9.0-pre) into an OTel Distribution (>= 0.10.0-alpha)
- [x] add note in CHANGELOG referring to old Honeycomb.OpenTelemetry 0.9.0-pre OTel Exporter and notes for how to pin to that version if not migrating to the new Honeycomb OTel Distro for DotNet

**Comment by MikeGoldsmith** [comment]
I've messaged Martin (community contributor who donated the original exporter) via Pollinators to explain what we're doing and why.

**Comment by robbkidd** [comment]
## "Fun" with Publishing

@JamieDanielson, @cartermp, and I mobbed on publishing to NuGet. 

### "Make sure you publish the symbols package"

OK.

[We updated](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/pull/63/commits/45b396968ac644956ba6c8940c0c8773232f58b4) the CircleCI `publish_nuget` job to upload `"build\*nupkg"` which we expected would match both the `.nupkg` and `.snupkg`. [It did not](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-dotnet/149/workflows/7a2c3486-71cb-409c-adad-875061950549/jobs/260).

```
error: File does not exist (build\*nupkg).
```

 `dotnet nuget push` apparently does not glob file paths like `ls` (confirmed on Phillip's Windows computer).

We deleted the release and the v0.10.0-alpha tag to try again.

### How about everything in `build/`?

[We updated](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/pull/64/files) the CircleCI `publish_nuget` job a second time to upload everything in `"build\"`.

1. This "[worked](https://www.nuget.org/packages/Honeycomb.OpenTelemetry/0.10.0-alpha)" ...
2. ... but didn't upload the symbols package (we think because we didn't [get specific about targeting a `.nupkg` for push](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#publishing-a-symbol-package)) ...
3. ... and **we thought the entire publish failed** because the job failed in the attempt to upload the `.snupkg` distinctly as picked up by the open-ended `"build\"` push target.

```
Pushing Honeycomb.OpenTelemetry.0.10.0-alpha.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Created https://www.nuget.org/api/v2/package/ 2535ms
Your package was pushed.
Pushing Honeycomb.OpenTelemetry.0.10.0-alpha.snupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  BadRequest https://www.nuget.org/api/v2/package/ 275ms
error: Response status code does not indicate success: 400 (Snupkg upload failed. Please use latest NuGet clients (v 4.9.0 or above) and a V3 endpoint to push Symbol packages. For details, refer https://docs.microsoft.com/nuget/create-packages/symbol-packages-snupkg).
```

We deleted the release and the v0.10.0-alpha tag to try again.

### How about going back to what works for libhoney-dotnet?

[We updated](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/pull/65/files) the CircleCI `publish_nuget` job a third time to go back to what @MikeGoldsmith had originally, before we tried to do anything with symbols packages. We tagged again and [this publish failed](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-dotnet/155/workflows/5cb8e70b-b216-4e32-99e8-fa7117ac8501/jobs/276) because the previous publish succeeded.

## What Now?

The [Honeycomb.OpenTelemetry 0.10.0-alpha package on NuGet](https://www.nuget.org/packages/Honeycomb.OpenTelemetry/0.10.0-alpha) should work, but (1) wasn't built from the current [v0.10.0-alpha tag in GitHub](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/commit/86c18378bb72875c9a72cad1675dde7018362db6), but maybe that's OK because (2) the symbols package didn't get uploaded?

* Can we remove a version of a package from NuGet? If so, we can remove it and try to publish 0.10.0-alpha _again_ and see if the latest change to the CircleCI publish_nuget job also publishes the symbols package.
* If not, we can wait for a 0.10.1+ release to sort out symbols.


## Maybe another change?

From the docs on [how to publish a symbols package](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#publishing-a-symbol-package) (emphasis mine):

> 3. You can also push both primary and symbol packages at the same time using the below command. Both .nupkg and .snupkg files need to be present _in the current folder._
>
> ```
> nuget push MyPackage.nupkg
> ```

A very literal reading of that says we ought to run the `dotnet nuget push` command with the `build/` directory as the current working directory and that the specific, complete `.nupkg` package filename is required to automatically publish the associated symbols package, too.

**Comment by cartermp** [comment]
> Can we remove a version of a package from NuGet?

Nope, NuGet is immutable. Must publish a new version. One additional thing you can do is mark a given package as unlisted, so it won't get picked up by client tooling (unless they request that specific version). But you need another version published after that.

> If not, we can wait for a 0.10.1+

This is probably what I'd do.

**Comment by cartermp** [comment]
Oh, right -- you can manually upload the symbols package for this _current_ package and it'll "line up" correctly. So long as that symbol package was built with the same NuGet package, it shouldn't cause any issue.

That doesn't solve the misalignment with tagging issue, though.

**Comment by robbkidd** [comment]
> NuGet is immutable.

As artifact repositories ought to be. 

![nod - this is correct](https://user-images.githubusercontent.com/517302/125856512-57d8601b-f869-4056-8bb7-7f625c5fde2d.gif)

> That doesn't solve the misalignment with tagging issue, though.

We ..._could_... delete the tag and put it back on the commit that produced the package that was published successfully. Which will trigger another build and publish ... whose publish will fail ... but that's maybe not worse than the current state?

**Comment by robbkidd** [comment]
Out of band conversation result: we're letting 0.10.0-alpha ride as is. We'll see whether the symbols publish on the next release and make whatever adjustments necessary on the one after that.

**Comment by MikeGoldsmith** [comment]
If we know which CI build successfully published the nupkg to nuget.org, we could replace the assets on the 0.10.0-alpha github release and manually publish the snupkg so they are totally inline.

PS you can use the `--skip-duplicates` switch to ignore duplicates so it won't fail if the nupkg was also present in the same local directory.

Going forward, I think the original push command with `build\*.nupkg` should be fine as it'll find the nupkg and push the symbols package along with it.

**Comment by MikeGoldsmith** [comment]
I've removed all individual owners of the Honeycomb.OpenTelemetry package on nuget (myself & original community donator). I've also generated a new API key for the CouchbaseAdmin nuget profile, added to LastPass and updated CircleCI.

**Comment by robbkidd** [comment]
> ... a new API key for the CouchbaseAdmin nuget profile ...

Did you mean HoneycombAdmin?
