### ISSUE TITLE
Investigate Stock OTel Configuration Experience

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-dotnet#73]
What is the Stock OTel Configuration experience with cmd line args, env vars, appsettings.json? Do they conflict? Is there a precedence hierarchy?

The intention here is to have this investigation inform what if any changes we would like to make to the beestro.

**Comment by robbkidd** [comment]
For environment variable configuration of stock OTel dotnet, I've had to use a naming convention that .NET uses to override appsettings (example: `export Otlp__Endpoint="https://api.honeycomb.io:443"`) instead of the standard OTLP exporter spec environment variables (example: `export OTEL_EXPORTER_OTLP_ENDPOINT="https://api.honeycomb.io:443"`. The only place I see the spec'd environment variable used in stock OTel dotnet is in the integration test where the _test itself_ [looks up the value of this environment variable](https://github.com/open-telemetry/opentelemetry-dotnet/blob/6b7f2dd77cf9d37260a853fcc95f7b77e296065d/test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/IntegrationTests.cs#L27-L28) to pass it to [an OtlpTraceExporter constructor](https://github.com/open-telemetry/opentelemetry-dotnet/blob/6b7f2dd77cf9d37260a853fcc95f7b77e296065d/test/OpenTelemetry.Exporter.OpenTelemetryProtocol.Tests/IntegrationTests.cs#L41-L46).

**Comment by robbkidd** [comment]
And [the PR merged](https://github.com/open-telemetry/opentelemetry-dotnet/pull/2188) with support for a few, but not all of the OTLP Exporter spec's environment variables.
